services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-student-service}:${TAG:-latest}
    container_name: student-service
    environment:
      APP_PORT: ${APP_PORT:-8080}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_pw}
    ports:
      - "${APP_PORT:-8080}:8080"
    restart: unless-stopped

